import Head from "next/head";
import { Inter } from "@next/font/google";
import { NextPage } from "next/types";
import { useQuery } from "@apollo/client";
import { graphql } from "../graphql/types";

const inter = Inter({ subsets: ["latin"] });

const GetBooksDocument = graphql(`
  query GetBooks {
    books {
      id
      name
    }
  }
`);

const Home: NextPage = () => {
  const { loading, data } = useQuery(GetBooksDocument);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <p className="text-blue-800 text-2xl font-medium">Quantum</p>

        <div>
          {loading ? (
            <p>Loading...</p>
          ) : (
            <div>{JSON.stringify(data?.books?.at(0)?.name)}</div>
          )}
        </div>
      </div>
    </>
  );
};

export default Home;
